export const POKE_LIST_REQUEST = 'POKE_LIST_REQUEST'
export const POKE_LIST_SUCCESS = 'POKE_LIST_SUCCESS'
export const POKE_LIST_FAIL = 'POKE_LIST_FAIL'

export const POKE_DETAILS_REQUEST = 'POKE_DETAILS_REQUEST'
export const POKE_DETAILS_SUCCESS = 'POKE_DETAILS_SUCCESS'
export const POKE_DETAILS_FAIL = 'POKE_DETAILS_FAIL'

export const POKE_ADD_REQUEST = 'POKE_ADD_REQUEST'
export const POKE_ADD_SUCCESS = 'POKE_ADD_SUCCESS'
